### ISSUE TITLE
trying to genaerate code but only a few lines of gcode

### ISSUE THREAD

**Issue by danaskew99** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#64]
here is what get every time it runs

M107 S0

G90
G21
G1 F1000
G1 X0 Y0

**Comment by mahboc** [comment]
Same Problem.  Inkscape 1.1.1 on Mac OSX 12.01.

/Users/j<user>/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions/laser/svg_to_gcode/compiler/_compiler.py:63: UserWarning: Compile with an empty body (no curves). Is this intentional?
  warnings.warn("Compile with an empty body (no curves). Is this intentional?")

**Comment by mahboc** [comment]
Make sure your objects and strokes are converted to paths or perhaps I should have RTFM :-(
