### ISSUE TITLE
Should pull-requests still support Python 2/Inkscape<1.0?

### ISSUE THREAD

**Issue by jtebert** [JTechPhotonics/J-Tech-Photonics-Laser-Tool#7]
The readme says to make sure your code works for Python 2 and 3, but in the releases it looks like there are now separate versions for Inkscape 1.0 and 0.9.

I have some improvement I've made to the code, but some are only compatible with Python 3. Should I undo those before submitting my pull request?

**Comment by PadLex** [comment]
Unfortunately the Inkscape 1.0 documentation says we should support both python versions because some users don't have python 3 installed. If JTech is okay with it, we will drop support for Python 2 in the next version to improve code readability. I'll create a new, python 3 only, development branch and you can make your pull request there.
